/* DO NOT EDIT THIS FILE - it is machine generated */
#include <taobao_com_hellojni_jni_Hello.h>
#include <log.h>
/* Header for class taobao_com_hellojni_jni_Hello */

JavaVM  *gJavaVm;
jobject gJobject;

//JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved){
//	LOGD("start init JNI");
//    gJavaVm = vm;
//    return 0;
//}

JNIEXPORT jint JNICALL Java_taobao_com_hellojni_jni_Hello_add
  (JNIEnv *, jclass jc, jint a, jint b){

    LOGD("enter JNI");
    LOGE("LOG ERROR %s","hello");
    return a+b;

}

JNIEXPORT void JNICALL Java_taobao_com_hellojni_jni_Hello_testCallback
  (JNIEnv *env, jobject thiz){

   LOGD("test callback");

    jclass clazz = env->GetObjectClass(thiz);

//    LOGD(thiz);
//    LOGD(clazz);
//    mMsgExtJObjectWeak = env->NewGlobalRef(weak_this);
    jobject obj = env->NewGlobalRef(clazz);
//    mCallbackJmethodId = env->GetStaticMethodID(clazz, "callbackFromNative", "(Ljava/lang/Object;)V");
//  jobject obj = (*env)->NewGlobalRef(env, clazz);

    jmethodID cb_method = env->GetStaticMethodID(obj, "onCallback","(Ljava/lang/String;)V");
//
//  (*env)->CallVoidMethod(env, obj, cb_method, 1);


//  struct Java_comm_taobao_acds_database_UnqliteDatabase_Ctx
//  {
//      jobject             obj;        //jni对象
//      char*               callback;   //jni回调名称
//      jint                callbackId; //jni回调id
//      char*               jx9Script;  //jx9教本
//  };
//
//  ctx->obj = (*env)->NewGlobalRef(env, obj);
//  		ctx->callback = strdup(callbackChar);
//  		ctx->callbackId = callbackId;
//          ctx->jx9Script = strdup(jx9Char);
//
//
//     JNIEnv *env=getJNIEnv(&needsDetach);
//
//      jstring resultStr = (*env)->NewStringUTF(env, result);
//
//      jclass cls = (*env)->GetObjectClass(env, ctx->obj);
//      jmethodID cb_method = (*env)->GetMethodID(env, cls, ctx->callback,"(I)V");
//      (*env)->CallVoidMethod(env, ctx->obj, cb_method, ctx->callbackId, code, resultStr);
//



}
