/* DO NOT EDIT THIS FILE - it is machine generated */
#include <taobao_com_hellojni_jni_Hello.h>
#include <log.h>
/* Header for class taobao_com_hellojni_jni_Hello */

JavaVM  *gJavaVm;
jobject gJobject;

//JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved){
//	LOGD("start init JNI");
//    gJavaVm = vm;
//    return 0;
//}

JNIEXPORT jint JNICALL Java_taobao_com_hellojni_jni_Hello_add
  (JNIEnv *, jclass jc, jint a, jint b){

    LOGD("enter JNI");
    LOGE("LOG ERROR %s","hello");
    return a+b;

}

//http://stackoverflow.com/a/18847493/2201207
//static method
JNIEXPORT void JNICALL Java_taobao_com_hellojni_jni_Hello_testCallback
  (JNIEnv *env, jclass cls){

    LOGD("test callback");

//    jclass cls = env->GetObjectClass(obj);
    jmethodID cb_method = env->GetStaticMethodID(cls, "onCallback","(I)V");

    env->CallStaticVoidMethod( cls, cb_method, 12345);

}


JNIEXPORT void JNICALL Java_taobao_com_hellojni_jni_Hello_testCallback2
  (JNIEnv *env, jobject obj){

    LOGD("test callback");

    jclass cls = env->GetObjectClass(obj);
    jmethodID cb_method = env->GetMethodID(cls, "onCallback2","(I)V");

    env->CallVoidMethod( obj, cb_method, 123456);

}
