/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class taobao_com_hellojni_jni_Hello */

#ifndef _Included_taobao_com_hellojni_jni_Hello
#define _Included_taobao_com_hellojni_jni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     taobao_com_hellojni_jni_Hello
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_taobao_com_hellojni_jni_Hello_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     taobao_com_hellojni_jni_Hello
 * Method:    testCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_taobao_com_hellojni_jni_Hello_testCallback
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_taobao_com_hellojni_jni_Hello_testCallback2
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
